version: '3.9'

networks:
  sample-netowrk:

volumes:
    grafana_data:
    logger_data:
    db_data:

services:

  sample-webapi:
    build:
      context: .
      dockerfile: ./docker/sample-webapi/Dockerfile
    environment:
      - FunctionsAppHostName=sample-functions
    ports:
      - 8081:80
    networks:
      - sample-netowrk

  sample-functions:
    build:
      context: .
      dockerfile: ./docker/sample-functions/Dockerfile
    ports:
      - 8082:80
    networks:
      - sample-netowrk

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - sample-netowrk

  grafana:
      image : grafana/grafana
      depends_on:
        - prometheus
      ports:
        - 3000:3000
      restart: always
      environment:
        - GF_AUTH_ANONYMOUS_ENABLED=true
      volumes:
        - grafana_data:/var/lib/grafana
        - ./docker/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
        - ./docker/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      networks:
        - sample-netowrk
