{
 "title": "Sample Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Web", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Exceptions Per Minute (Last 5 minutes)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job) (rate(sample_total_exceptions[5m]) * 60)"
    }
   ]
  },
  {
   "title": "Total Exceptions",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "sum without(instance)(sample_total_exceptions)"
    }
   ]
  },
  {
   "title": "Total Exceptions Per Instance",
   "type": "table",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum without(exception_type)(sample_total_exceptions)"
    }
   ]
  },
  {
   "title": "Application Info",
   "type": "table",
   "gridPos": { "h": 7, "w": 17, "x": 0, "y": 9 },
   "targets": [
    { "expr": "app_info" }
   ]
  }
 ]
}