name: bicep test

on:
  workflow_dispatch:
  push:
    branches: '*'

env:
  AZURE_RESOURCE_GROUP_NAME: mattk09-centralus
  AZURE_RESOURCE_GROUP_LOCATION: centralus

jobs:
  deploy-resources:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Test az cli
      run: |
        az account show
        echo "AZURE_SUBSCRIPTION_ID=$(az account show --query "id" --output tsv)" >> $GITHUB_ENV

    - uses: Azure/CLI@v1
      with:
        inlineScript: |
          #!/bin/bash
          az group create --name $AZURE_RESOURCE_GROUP_NAME --location $AZURE_RESOURCE_GROUP_LOCATION

    - name: Deploy bicep
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ env.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP_NAME }}
        template: ./bicep/main.bicep
        failOnStdErr: false

    - name: Last step diagnostics
      if: always()
      run: |
        pwd
        printenv | sort
        ls -R

