name: dotnet build and deploy

on:
  workflow_dispatch:
    inputs:
      resource-group-name:
        required: false
        type: string
  push:
    branches:
    paths:
    - .github/workflows/dotnet.yml
    - bicep/main.bicep
    - bicep/modules/**
    - src/**
  pull_request:
    branches: [ main ]

env:
  IS_MAIN_PUSH: ${{ github.ref == 'refs/heads/main' }}
  AZURE_RESOURCE_GROUP_NAME: ${{ github.event.inputs.resource-group-name || 'mattk09-centralus' }}
  AZURE_RESOURCE_GROUP_LOCATION: centralus
  BUILD_CONFIGURATION: Release
  DOTNET_VERSION: 6.0.x
  ADDITIONAL_KEY_VAULT_SECRETS: >-
    {
      \"secrets\": [
          {\"name\": \"Sample--Secret\", \"secret\": \"Sample-Secret\" }
      ]
    }

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal --settings coverlet.runsettings.xml

    - name: Code Coverage
      run: |
        dotnet tool install --tool-path . dotnet-reportgenerator-globaltool
        mkdir code-coverage
        ./reportgenerator -reports:./**/coverage.cobertura.xml -targetdir:./code-coverage -reporttypes:Cobertura

    - name: Publish Code Coverage
      uses: actions/upload-artifact@v2
      with:
        name: sample-code-coverage
        path: ./code-coverage/Cobertura.xml

    - name: Publish WebApi
      if: success() && (env.IS_MAIN_PUSH == 'true' || github.event_name == 'workflow_dispatch')
      run: dotnet publish src/Sample.WebApi/Sample.WebApi.csproj --configuration ${{ env.BUILD_CONFIGURATION }} --output published/Sample.WebApi

    - name: Upload WebApi Build Artifact
      if: success() && (env.IS_MAIN_PUSH == 'true' || github.event_name == 'workflow_dispatch')
      uses: actions/upload-artifact@v2
      with:
        name: Sample.WebApi
        path: published/Sample.WebApi

    - name: Publish Functions
      if: success() && (env.IS_MAIN_PUSH == 'true' || github.event_name == 'workflow_dispatch')
      run: dotnet publish src/Sample.Functions/Sample.Functions.csproj --configuration ${{ env.BUILD_CONFIGURATION }} --output published/Sample.Functions

    - name: Upload Functions Build Artifact
      if: success() && (env.IS_MAIN_PUSH == 'true' || github.event_name == 'workflow_dispatch')
      uses: actions/upload-artifact@v2
      with:
        name: Sample.Functions
        path: published/Sample.Functions

    - name: Last step diagnostics
      if: always()
      run: |
        pwd
        printenv | sort
        ls -alFR -I.git

  deploy:

    runs-on: ubuntu-latest
    needs: build
    if: (github.ref == 'refs/heads/main' && github.event_name == 'push') || (github.event_name == 'workflow_dispatch')

    steps:
    - uses: actions/checkout@v2

    - name: Download Sample.WebApi
      uses: actions/download-artifact@v2.0.8
      with:
        name: Sample.WebApi
        path: packages/Sample.WebApi

    - name: Download Sample.Functions
      uses: actions/download-artifact@v2.0.8
      with:
        name: Sample.Functions
        path: packages/Sample.Functions

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set current Azure Subscription
      run: |
        az account show
        echo "AZURE_SUBSCRIPTION_ID=$(az account show --query "id" --output tsv)" >> $GITHUB_ENV
        echo "Logged in! 🎉"

    - name: Create Azure Resource Group
      uses: Azure/CLI@v1
      with:
        inlineScript: |
          #!/bin/bash
          az group create --name $AZURE_RESOURCE_GROUP_NAME --location $AZURE_RESOURCE_GROUP_LOCATION

    - name: Deploy bicep 💪
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ env.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP_NAME }}
        template: ./bicep/main.bicep
        failOnStdErr: false
        parameters: >-
          additionalSecrets="${{ env.ADDITIONAL_KEY_VAULT_SECRETS }}"
          developerObjectIdKeyVaultAccessPolicy="${{ secrets.AZURE_DEVELOPER_OBJECT_ID }}"

    - name: Deploy Sample.WebApi
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_RESOURCE_GROUP_NAME }}
        package: packages/Sample.WebApi

    - name: Deploy Sample.Functions
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_RESOURCE_GROUP_NAME }}-functions
        package: packages/Sample.Functions

    - name: Last step diagnostics
      if: always()
      run: |
        pwd
        printenv | sort
        ls -alFR -I.git
