name: dotnet build

on:
  workflow_dispatch:
  push:
    branches:
  pull_request:
    branches: [ main ]

env:
  IS_MAIN_PUSH: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
  AZURE_RESOURCE_GROUP_NAME: mattk09-centralus
  AZURE_RESOURCE_GROUP_LOCATION: centralus
  BUILD_CONFIGURATION: Release
  DOTNET_VERSION: 6.0.x

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal --settings coverlet.runsettings.xml

    - name: Publish WebApi
      if: success() && env.IS_MAIN_PUSH == 'true'
      run: dotnet publish src/Sample.WebApi/Sample.WebApi.csproj --configuration ${{ env.BUILD_CONFIGURATION }} --output published/Sample.WebApi

    - name: Upload WebApi Build Artifact
      if: success() && env.IS_MAIN_PUSH == 'true'
      uses: actions/upload-artifact@v2
      with:
        name: Sample.WebApi
        path: published/Sample.WebApi

    - name: Publish Functions
      if: success() && env.IS_MAIN_PUSH == 'true'
      run: dotnet publish src/Sample.Functions/Sample.Functions.csproj --configuration ${{ env.BUILD_CONFIGURATION }} --output published/Sample.Functions

    - name: Upload Functions Build Artifact
      if: success() && env.IS_MAIN_PUSH == 'true'
      uses: actions/upload-artifact@v2
      with:
        name: Sample.Functions
        path: published/Sample.Functions

    - name: Last step diagnostics
      if: always()
      run: |
        pwd
        printenv | sort
        ls -alFR -I.git

  deploy:

    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
    - uses: actions/checkout@v2

    - name: Download Sample.WebApi
      uses: actions/download-artifact@v2.0.8
      with:
        name: Sample.WebApi
        path: packages/Sample.WebApi

    - name: Download Sample.Functions
      uses: actions/download-artifact@v2.0.8
      with:
        name: Sample.Functions
        path: packages/Sample.Functions

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set current Azure Subscription
      run: |
        az account show
        echo "AZURE_SUBSCRIPTION_ID=$(az account show --query "id" --output tsv)" >> $GITHUB_ENV

    - name: Create Azure Resource Group 
      uses: Azure/CLI@v1
      with:
        inlineScript: |
          #!/bin/bash
          az group create --name $AZURE_RESOURCE_GROUP_NAME --location $AZURE_RESOURCE_GROUP_LOCATION

    - name: Deploy bicep
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ env.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP_NAME }}
        template: ./bicep/main.bicep
        failOnStdErr: false

    - name: Deploy Sample.WebApi
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_RESOURCE_GROUP_NAME }}
        package: packages/Sample.WebApi

    - name: Deploy Sample.Functions
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_RESOURCE_GROUP_NAME }}-functions
        package: packages/Sample.Functions

    - name: Last step diagnostics
      if: always()
      run: |
        pwd
        printenv | sort
        ls -alFR -I.git
