name: deploy and manage workflow key vault

on:
  workflow_dispatch:
    inputs:
      resource-group-name:
        required: false
        type: string
  push:
    branches:
    paths:
    - .github/workflows/workflow-key-vault.yml

env:
  IS_MAIN_PUSH: ${{ github.ref == 'refs/heads/main' }}
  AZURE_RESOURCE_GROUP_NAME: ${{ github.event.inputs.resource-group-name || 'mattk09-workflow-centralus' }}
  AZURE_RESOURCE_GROUP_LOCATION: centralus

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set current Azure Subscription
      run: |
        az account show
        echo "AZURE_SUBSCRIPTION_ID=$(az account show --query "id" --output tsv)" >> $GITHUB_ENV
        echo "Logged in! 🎉"

    - name: Create Azure Resource Group
      uses: Azure/CLI@v1
      with:
        inlineScript: |
          #!/bin/bash
          az group create --name $AZURE_RESOURCE_GROUP_NAME --location $AZURE_RESOURCE_GROUP_LOCATION

    - name: Generate SSH Keys
      run: |
        mkdir keys
        ssh-keygen -m PEM -t rsa -b 4096 -N '' -f ./keys/ssh.pem

        whoami
        sudo chmod 444 ./keys/ssh.pem.pub
        echo "SSH_PEM_PUB='$(./keys/ssh.pem.pub)'" >> $GITHUB_ENV

        # echo "SSH_PEM='$(cat ./keys/ssh.pem)'" >> $GITHUB_ENV
        echo 'SSH_PEM<<EOF' >> $GITHUB_ENV
        cat ./keys/ssh.pem >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV

        echo "Generated keys! 🎉"

    - name: Prepare secrets for key vault
      id: prepare-secrets
      env:
        ADDITIONAL_KEY_VAULT_SECRETS: >-
          [
              {"sshPrivate": "Sample--Secret", "secret": "$SSH_PEM" },
              {"sshPublic": "Sample--Secret", "secret": "Sample-Secret" }
          ]
      run: |
        echo "::set-output name=key-vault-secrets::$(echo $ADDITIONAL_KEY_VAULT_SECRETS | jq -MRc)"

    - name: Deploy bicep 💪
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ env.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP_NAME }}
        template: ./bicep/main-workflow-key-vault.bicep
        failOnStdErr: false
        parameters: >-
          developerObjectIdKeyVaultAccessPolicy="${{ secrets.AZURE_DEVELOPER_OBJECT_ID }}"
          additionalSecrets=${{ steps.prepare-secrets.outputs.key-vault-secrets }}


    - name: Last step diagnostics
      if: always()
      run: |
        pwd
        printenv | sort
        ls -alFR -I.git