trigger:
  branches:
    include:
      - '*'
  paths:
    include:
      - docs/*

pool:
  vmImage: ubuntu-latest
  demands: npm

jobs:
- job: DocumentsLint
  steps:
  - task: NodeTool@0
    displayName: Install node
    inputs:
      versionSpec: 10.x

  - script: npm install -g cspell markdownlint-cli
    displayName: Install CSpell and Markdown lint

  - script: cspell "docs/**/*.md"  --config $(Build.SourcesDirectory)/azure-pipelines/cspell/cspell.json
    displayName: Run CSpell

  - script: |
      set -e
      markdownlint "docs/**/*.md" --config $(Build.SourcesDirectory)/azure-pipelines/mdlint/mdlint.json
    displayName: Run Markdown Lint